### ISSUE TITLE
Fresh install

### ISSUE THREAD

**Issue by spot88** [MikkelDK/GameServerKernel#3]
Hi, new trying this Kernal. 

Is there anything else i need to do for this to work when i see it's been installed korrekt?
"Welcome to Ubuntu 18.04.3 LTS (GNU/Linux 5.3.8-custom x86_64)"

**Comment by MikkelDK** [comment]
Try ``uname -a``

**Comment by spot88** [comment]
Thanks for quick reply. It goes auto on 1000Hz? 
Got this after the uname -a "5.3.8-custom #1 SMP PREEMPT Mon Nov 4 14:13:37 CET 2019 x86_64 x86_64 x86_64 GNU/Linux"

**Comment by MikkelDK** [comment]
Yep. it is =)
